### ISSUE TITLE
why three binds?

### ISSUE THREAD

**Issue by timm** [yrahul3910/csc591-s23#2]
https://github.com/yrahul3910/csc591-s23/blob/e78074ebeb046c5aa545bd98bbb54e38e59f27e1/Sym.js#L6-L8

**Comment by yrahul3910** [comment]
`bind` allows those functions to access `this`, see [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/bind).
